package soon.io.soon.models.notification;

public enum NotificationTypes {
    NOTIFICATION_ORDER_ACCEPTED,
    NOTIFICATION_ORDER_REJECTED,
    NOTIFICATION_ORDER_PREPARING,
    NOTIFICATION_ORDER_DELIVERED,
    NOTIFICATION_DROPBOX_CONFIGURATION
}
